### ISSUE TITLE
Error: Failed to execute 'fetch' on 'Window': The user aborted a request.  

### ISSUE THREAD

**Issue by vikashs2022** [coveooss/headless-starter#15]
![Screenshot 2023-04-28 at 12 34 20 PM](https://user-images.githubusercontent.com/97214660/235237343-246b82bc-b042-47de-8e2d-2fea358316ef.png)

Given the vulnerabilities reported by create-react-app, I am using vite for the starter package and code is the same. The search continues to function but would to know the reason for this error.
Cheers, Vikas

**Comment by jpmarceau** [comment]
Hello Vikas, thanks for reporting this issue. It highlights the fact that we should've redirected users to the new tutorial and starter repo, which address the issues of this repo.
https://levelup.coveo.com/learn/courses/headless-commerce-tutorial
https://github.com/coveooss/headless-commerce-tutorial
This repo here will be archived
